# Generated by Django 4.0.5 on 2022-07-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=11, verbose_name='Юзернейм'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_telegram_id',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Юзер-айди'),
        ),
    ]
